<?php
use Magento\Framework\App\Action\Action;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
$widgetSliderId = $this->getData('widget_coreway_slider_id');
$widgetSliderData = $block->getWidgetSliderData($widgetSliderId);
$productConfiguration = $block->getProductConfigurationStatus();
$sliderConfiguration = $block->getProductSliderConfigurationStatus();

if (count($widgetSliderData) > 0) {
    $attrCode = $widgetSliderData["coreway_product_slider_attribute_code"];
    $attrValue = $widgetSliderData["coreway_product_slider_attribute_value"];
    $categoryId = $widgetSliderData["coreway_product_slider_category_id"];
    $productNumber = $widgetSliderData["coreway_product_slider_number"];
    $collection = $block->getSliderProductData($attrCode, $attrValue, $categoryId, $productNumber);
    if (count($collection) > 0) {
    ?>
<div class="product-slider-wrapper">
   <div class="block block-product-slider slider-list">
        <?php if (isset($widgetSliderData["coreway_product_slider_name"]) && $widgetSliderData["coreway_product_slider_name"] != "") : ?>
        <div class="block-title title">
            <strong id="block-heading" role="heading"><?= /* @escapeNotVerified */ $widgetSliderData["coreway_product_slider_name"]; ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content content" >
        <div class="products wrapper grid products-grid">
           <ol class="products list items Coreway-product-slider">        		
        		<?php foreach ($collection as $_item) { ?>
        			<li class="item product product-item">
	                	<?php
	                	$prdoductLoop=$_item;
                        $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
                        $product_image = $imageHelper->init($prdoductLoop, 'product_base_image')->setImageFile($prdoductLoop->getFile())->getUrl();
                        $productUrl  = $prdoductLoop->getProductUrl();
                        ?>
                        <div class="product-item-info">
	                        <?php
	                        $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');

							$productImage = $imageBlock->getImage($prdoductLoop, 'category_page_list');
							if ($productConfiguration["product_image"] == "1") {
							?>
							<a href="<?= /* @escapeNotVerified */ $productUrl; ?>"><?= /* @escapeNotVerified */ $productImage->toHtml()  ?></a>
							<?php } ?>
							<div class="product details product-item-details">
								<?php if ($productConfiguration["product_name"] == "1") { ?>
	                            <strong class="product name product-item-name">
	                            	<a class="product-item-link" title="<?= /* @escapeNotVerified */ $prdoductLoop->getName(); ?>" href="<?= /* @escapeNotVerified */ $productUrl; ?>"><?= /* @escapeNotVerified */ $prdoductLoop->getName(); ?></a>
	                            </strong>
	                        	<?php } ?>

	                        	<?php if ($productConfiguration["product_review"] == "1") { ?>
	                            	<?= /* @escapeNotVerified */ $block->getReviewsSummaryHtml($prdoductLoop, $templateType = false, $displayIfNoReviews = false); ?>
	                        	<?php } ?>

	                        	<?php if ($productConfiguration["product_price"] == "1") { ?>
	                            	<?= /* @escapeNotVerified */ $block->getProductPrice($prdoductLoop); ?>
	                            <?php } ?>
	                            
	                            <div class="product-item-inner">
		                            <div class="product actions product-item-actions">
		                                <?php if ($productConfiguration["product_cart"] == "1") { ?>
		                                <div class="actions-primary">
		                                    <?php if ($prdoductLoop->isSaleable()): ?>
		                                        <?php 
                                                $postParams = $block->getAddToCartPostParams($prdoductLoop); 
                                                $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
                                                $addToCartUrl =  $listBlock->getAddToCartUrl($prdoductLoop);
                                                ?>
		                                        <form data-role="tocart-form" data-product-sku="<?= /* @escapeNotVerified */ $block->escapeHtml($prdoductLoop->getSku()) ?>" action="<?= /* @NoEscape */ $addToCartUrl ?>" method="post">
		                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
		                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
		                                            <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey') ?>
		                                            <button type="submit"
		                                                    title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Add to Cart')) ?>"
		                                                    class="action tocart primary">
		                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
		                                            </button>
		                                        </form>
		                                    <?php else: ?>
		                                        <?php if ($prdoductLoop->isAvailable()) : ?>
		                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
		                                        <?php else : ?>
		                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
		                                        <?php endif; ?>
		                                    <?php endif; ?>
		                                </div>
		                            	<?php } ?>
		                                <div class="actions-secondary" data-role="add-to-links">
		                                	<?php if ($productConfiguration["product_wishlist"] == "1") { ?>
										    <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($prdoductLoop); ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= /* @escapeNotVerified */ __("Add to Wish List"); ?>">
										    	<span><?= /* @escapeNotVerified */ __("Add to Wish List"); ?></span>
										    </a>                                                                                                                 <?php } ?>

										    <?php if ($productConfiguration["product_compare"] == "1") { ?>
										    <a href="#" class="action tocompare" title="<?= /* @escapeNotVerified */ __("Add to Compare"); ?>" aria-label="<?= /* @escapeNotVerified */ __("Add to Compare"); ?>" data-post='<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($prdoductLoop); ?>' role="button">
										    	<span><?= /* @escapeNotVerified */ __("Add to Compare"); ?></span>
										    </a>
										    <?php } ?>

										</div>
		                            </div>
		                        </div>
	                        </div>
	                    </div>
	                </li>
	                
            	<?php } ?>
            </ol>
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
    require(['jquery', 'slick'], function($){
        $(function(){
            $('ol.Coreway-product-slider.list.items').slick({
                dots: <?= /* @escapeNotVerified */ $sliderConfiguration["navigation"]; ?>,
                infinite: <?= /* @escapeNotVerified */ $sliderConfiguration["infinite"]; ?>,
                slidesToShow: 4,
                slidesToScroll: 1,
                speed: 500,
                autoplay:<?= /* @escapeNotVerified */ $sliderConfiguration["autoplay"]; ?>,
                autoplaySpeed:<?= /* @escapeNotVerified */ $sliderConfiguration["speed"]; ?>,
                cssEase: 'linear',
                rtl: false,
                responsive: [
                    {
                     breakpoint: 1025,
                     settings: {
                       slidesToShow: 3,
                       slidesToScroll: 1
                     }
                   },
                   {
                     breakpoint: 641,
                     settings: {
                       slidesToShow: 2,
                       slidesToScroll: 1
                     }
                   },
                   {
                     breakpoint: 376,
                     settings: {
                       slidesToShow: 1,
                       slidesToScroll: 1
                     }
                   }
                ]
            })
        })
    });
</script>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>

<?php } ?>
<?php } ?>
